# Generated by Django 3.1.1 on 2020-09-30 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done')], default='To Do', max_length=10)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('fk_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task_create', to=settings.AUTH_USER_MODEL)),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manage_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
