# Generated by Django 3.1.1 on 2020-09-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To Do', 'To Do'), ('Doing', 'Doing'), ('Done', 'Done')], default='To Do', max_length=10),
        ),
    ]
