# Generated by Django 3.1.1 on 2020-09-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=95)),
                ('role', models.CharField(choices=[(0, 'Manager'), (1, 'Administrator')], max_length=15)),
                ('password', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
